In [1]:
#Import Libraries


import numpy as np
import pandas as pd
import os
import csv
import re
from pdfminer import high_level
import nltk
from nltk.tokenize import word_tokenize
nltk. download("punkt")

[nltk_data] Downloading package punkt to /home/samanvitha/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [2]:
#Function to extract Phone Numbers from string using regular expressions
def extract_phone_numbers(string):
    r = re.compile(r'(\d{3}[-\.\s]??\d{3}[-\.\s]??\d{4}|\(\d{3}\)\s*\d{3}[-\.\s]??\d{4}|\d{3}[-\.\s]??\d{4})')
    phone_numbers = r.findall(string)
    #return [re.sub(r'\D', '', number) for number in phone_numbers]
    
    numbers = [re.sub(r'\D', '', number) for number in phone_numbers]
    for item in numbers:
        if len(item) == 10 or len(item) == 14:
            return item

In [3]:
def extract_email_addresses(string):
    r = re.compile(r'[\w\.-]+@[\w\.-]+') 
    return r.findall(string)

In [7]:
with open('techskill.csv', newline='') as csvfile:
        data = list(csv.reader(csvfile))
        
def extract_skills(extracted_text):
    skills = " "
   
    a_list = nltk. word_tokenize(extracted_text.lower()) #Split text into list of words.
    for item in data:
        for sub_item in item:
            if sub_item in a_list:
                skills = skills + sub_item + " "
    return skills

In [8]:

d = 'Resumes'
cols = ["name","phone_number","email","skills"]
rows = []
def select_files_in_folder(d, ext):
    for file in os.listdir(d):
        if file.endswith('.%s' % ext):
            yield os.path.join(d, file)


for file in select_files_in_folder(d, 'pdf'):
    pages = [0,1] # just the first page
    extracted_text = high_level.extract_text(file, "", pages)
    #name = extract_names(extracted_text)
    name = file[8:(len(file))-4]
    phone_number = extract_phone_numbers(extracted_text)
    email = extract_email_addresses(extracted_text)
    skills = extract_skills(extracted_text)
    rows.append({'name': name,
                     'phone_number':phone_number,
                        'email':email[0],
                         'skills':skills})
out_df = pd.DataFrame(rows, columns = cols)

In [9]:
print(out_df)

                                                 name phone_number  \
0                                 Abhijay Kumar Singh   7760380991
1                Apoorva_R_Resume - Apoorva Bharadwaj   7204441749
2                      HEMANTH_Resume - Hemanth Kumar   8553290086
3                                           Koushik J   7349713094
4                                        Sahana Gowda   8296650819
5           Amogha_Subramanya - Amogha Subramanya D A   8553511856
6                              newresume - Hiba Iqbal   9731618840
7                                        Akshay Anand   9431913301
8   Divya_Madhav_Kamath_Resume_April42018 - Divya ...   9591721577
9                                          Nandan K R   9480233978
10                 Anoop_Bhat_N_Resume - Anoop bhat n   9900831736
11                                    Madgula Mahathi   7981392446
12                                      Sumangala Rao   9191645227
13                                    Manasa Kanathur   9902206706
14                               SRM_ML - Sourabh R M   9880125575
15                                       Sushil Kumar   9631713085
16                       Resume_july - Rakesh gourani   9164260924
17                         praveen-resume - Praveen G   9743175960
18                                            Medha K   8749037897
19                                 Harsha - Harsha Bm   9174119699
20                                           Ahalya R   8971774677
21                                    Siddhant Sharma   9742572913
22                                       Rutwik Nayak   9964442953
23                           PradeepPai - Pradeep Pai   8971743181
24                                    Shaheed Nehal A   7406740089
25                          updatedCV - sandesh hegde   9196635857
26                                 Kanakam Sai Dimple   8867419797
27                                           Aarthi T   8762068961
28                                Arunima Rashmi Giri   8971636350
29                                       Amogh Mahesh   8050203235
30              Abhishek_Bisht - Abhishek Singh Bisht   9738959449
31                                         Vijeth V K   9731362817
32                           Nikhil Prabhakar Kottary   9187489821
33                     WD resume - ashwin bhadravathi   8892369197
34                                    Ashritha Shetty   9191081432
35                     Resume2.3 - Niveditha Somayaji   9901476977
36                        Docs_Resume1.3 - Spoorthi M   7795912621
37                                     AJAYB - AJAY B   8904636160
38                                         T S Kushal   9449938598
39                                       Aravinda S V   9901960855
40                                  K V Sampritha Rao   9148180450
41                                     Shripriya Bhat   9591682304
42                                       Samanvitha_S   8904868690
43                                       Shwet Sharma   9482026516
44                                   Meghana A Rajeev   9481325094
45                Yogeesh Rajendra Resume - YOGEESH R   9480560233

                            email  \
0           abhijayks98@gmail.com
1    apoorvabharadwaj02@gmail.com
2           hemanthkm05@gmail.com
3          koushikj9823@gmail.com
4        sahanagowda146@gmail.com
5    amoghasubramanya17@gmail.com
6          hibaiqbal781@gmail.com
7      akshayanand.2808@gmail.com
8     divyamadhavkamath@gmail.com
9            nandankr74@gmail.com
10           anoopnbhat@gmail.com
11       madgulamahathi@gmail.com
12        sumangala3rao@gmail.com
13       manasakanathur@gmail.com
14        sourabhraja97@gmail.com
15         sushilsoni39@gmail.com
16    rakeshgourani1740@gmail.com
17         praveen.g126@gmail.com
18         medhakalkura@gmail.com
19         bmharsha18jc@gmail.com
20           ahalya.r22@gmail.com
21     siddhantsharma97@gmail.com
22         rutwik.nayak@gmail.com
23        paipradeep512@gmail.com
24         shahidnehala@gmail.com
25        sandeshhegde9@gmail.com
26          dimple.1698@gmail.com
27          aarthi.t.29@gmail.com
28        arunimagiri13@gmail.com
29             amoghm14@gmail.com
30     abhisinghbisht04@gmail.com
31           vijethvk11@gmail.com
32     nikhil.p.kottary@gmail.com
33         ashwinsjce97@gmail.com
34     ashrithashetty27@gmail.com
35   nivedithansomayaji@gmail.com
36         spoorthi2112@gmail.com
37         balajiajay97@gmail.com
38       t.s.kushal9919@gmail.com
39              aravisv@gmail.com
40        sampritharao5@gmail.com
41        bhatshripriya@gmail.com
42  samanvitha.sateesha@gmail.com
43     shwet.condinya96@gmail.com
44      meghana.arakkal@gmail.com
45        yogeesh.srkvs@gmail.com

                                               skills
0                   mysql anaconda python python c++
1    algorithms cryptography mysql tensorflow anac...
2             threading mysql python python parser c
3    mysql python jupyter python javascript php c+...
4    algorithms mysql dataset python python mock g...
5    algorithms mysql anaconda python spyder jupyt...
6    flower queries dataset visual python python c...
7    algorithms pandas seaborn mysql python kivy m...
8    algorithms mysql keras python pillow nltk pyt...
9            mysql keras ansible python python css c
10   dataset python spark xgboost python framework c
11   mysql dataset python django python django jav...
12   opencv open python curses python open mixer c...
13   algorithms mysql postgresql python python jav...
14   matplotlib mysql postgresql keras tensorflow ...
15                 mysql python python php c++ css c
16   algorithms opencv python logging python robot...
17        tensorflow python interactive python c++ c
18                        opencv python python c++ c
19                     mysql dataset python python c
20                 mysql python python php c++ css c
21   flower keras python django python framework d...
22   mysql tensorflow anaconda python spyder djang...
23   algorithms open dataset python python open gr...
24   algorithms try python django python django c+...
25         algorithms dataset python python github c
26   algorithms open mysql keras python kivy pygam...
27   algorithms mysql python python github c++ css c
28   libraries libraries pandas seaborn python lib...
29   algorithms opencv mysql keras tensorflow anac...
30   python tkinter pattern python github javascri...
31   supervisor anaconda python spyder jupyter pyt...
32   opencv mysql keras anaconda python spyder jup...
33   threading dataset python interactive python p...
34         mysql dataset python python php c++ css c
35              mysql visual python python c++ css c
36   mysql dataset anaconda python spyder jupyter ...
37   mysql dataset keras tensorflow anaconda pytho...
38                     mysql python python php c++ c
39   mysql python spyder jupyter python php c++ cs...
40                   mysql visual wifi php c++ css c
41   mysql money python python github javascript c...
42   mysql python python github javascript c++ css c
43                               mysql php c++ css c
44   opencv open mysql tensorflow python spyder ju...
45              click try merchant plan shell matlab

In [10]:
out_df.to_excel('big_data_df.xlsx')